from typing import Any, Protocol, runtime_checkable

@runtime_checkable
class StorageBackend(Protocol):
    """3O Standard Storage Backend Protocol."""
    def put_node(self, node_id: str, payload: dict[str, Any]) -> None: ...
    def get_node(self, node_id: str) -> dict[str, Any] | None: ...
    def list_nodes(self) -> list[str]: ...
    def put_edge(self, src_id: str, relation: str, dst_id: str) -> None: ...
    def list_edges(self, node_id: str | None = None) -> list[dict[str, Any]]: ...

@runtime_checkable
class EpistemicStore(Protocol):
    """AII Specific Epistemic Storage Protocol."""
    def put_ku(self, ku: dict[str, Any]) -> None: ...
    def get_ku(self, ku_id: str) -> dict[str, Any] | None: ...
    def query_ku_by_grade(self, grade: str) -> list[dict[str, Any]]: ...
    def search_ku_by_vector(self, query_vector: list[float], limit: int = 5) -> list[dict[str, Any]]: ...
    def record_state_change(self, ku_id: str, to_grade: str, reason: str | None = None, decision_trail: dict[str, Any] | None = None) -> None: ...
    def quarantine_ku(self, ku_id: str, reason: str) -> None: ...
