-- Feed subscription management (Phase 17.7)
-- Uses DuckDB syntax (no UUID type; use TEXT for IDs generated by ULID generator)

CREATE TABLE IF NOT EXISTS feed_subscriptions (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    feed_url TEXT NOT NULL,
    feed_title TEXT,
    feed_description TEXT,
    frequency_hours INTEGER DEFAULT 6,
    last_check_at TIMESTAMP,
    last_etag TEXT,
    last_modified TEXT,
    last_entries_count INTEGER DEFAULT 0,
    status TEXT DEFAULT 'active',
    error_message TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    UNIQUE (user_id, feed_url)
);

CREATE INDEX IF NOT EXISTS idx_feed_subs_user ON feed_subscriptions (user_id);
CREATE INDEX IF NOT EXISTS idx_feed_subs_status ON feed_subscriptions (status);
