#!/usr/bin/env python3
"""Generate PostgreSQL DDL for the `stratum` schema from the live DuckDB schema dump.

P1.1 of the AII merge (DB convergence). Reads _schema_dump.json (produced by
introspecting the live DuckDB) and emits faithful PG `CREATE TABLE stratum.<t>`
DDL. The `stratum` schema lives alongside AII's `aii` schema in aii-postgres.

Type mapping (DuckDB -> PG):
  VARCHAR        -> TEXT
  VARCHAR[]      -> TEXT[]
  JSON           -> JSONB
  TIMESTAMP      -> TIMESTAMPTZ
  FLOAT[1024]    -> vector(1024)   (pgvector; matches AII / BGE-M3)
  FLOAT/DOUBLE   -> DOUBLE PRECISION
  BIGINT/INTEGER/BOOLEAN/DATE -> same

Search columns (tsvector / substrate embeddings) are added later in P1.4, not here.
Legacy pre-merge duplicate tables are skipped.
"""
import json
import re
import sys

# Pre-merge legacy duplicates superseded by the *_s / plural live tables.
SKIP_TABLES = {"substrate", "concept", "note", "_migrations"}

PK_OVERRIDE = {
    "share_tokens": "token",
    "blocked_ips": "ip_address",
    "user_profiles": "user_id",
    "changefeed": "seq",
    "changefeed_local": "seq",
    "arxiv_processed_papers": None,      # composite / no single PK — leave unconstrained
    "channel_processed_videos": None,
    "source_processed_items": None,
    "arxiv_subscriptions": "id",
}


def map_type(dt: str) -> str:
    dt = dt.strip()
    m = re.match(r"^FLOAT\[(\d+)\]$", dt)
    if m:
        return f"vector({m.group(1)})"
    if dt.endswith("[]"):
        return map_type(dt[:-2]) + "[]"
    base = {
        "VARCHAR": "TEXT",
        "JSON": "JSONB",
        "TIMESTAMP": "TIMESTAMPTZ",
        "TIMESTAMP WITH TIME ZONE": "TIMESTAMPTZ",
        "FLOAT": "DOUBLE PRECISION",
        "DOUBLE": "DOUBLE PRECISION",
        "HUGEINT": "NUMERIC",
        "BIGINT": "BIGINT",
        "INTEGER": "INTEGER",
        "BOOLEAN": "BOOLEAN",
        "DATE": "DATE",
        "BLOB": "BYTEA",
    }
    return base.get(dt, "TEXT")  # safe fallback


def main() -> int:
    dump_path = sys.argv[1] if len(sys.argv) > 1 else "_schema_dump.json"
    schema = json.load(open(dump_path, encoding="utf-8"))

    out = [
        "-- Generated by scripts/pg_schema_gen.py — P1.1 DB convergence (DuckDB -> PG).",
        "-- Non-destructive: creates the `stratum` schema; does NOT touch `aii`.",
        "CREATE EXTENSION IF NOT EXISTS vector;",
        "CREATE SCHEMA IF NOT EXISTS stratum;",
        "",
    ]
    tables = [t for t in sorted(schema) if t not in SKIP_TABLES]
    for t in tables:
        cols = schema[t]
        colnames = {c["col"] for c in cols}
        pk = PK_OVERRIDE.get(t, "id" if "id" in colnames else None)
        lines = []
        for c in cols:
            pg_type = map_type(c["type"])
            null = "" if c["null"] == "YES" else " NOT NULL"
            is_pk = pk and c["col"] == pk
            # PK implies NOT NULL; keep declaration clean.
            suffix = " PRIMARY KEY" if is_pk else null
            lines.append(f'    "{c["col"]}" {pg_type}{suffix}')
        out.append(f"CREATE TABLE IF NOT EXISTS stratum.{t} (")
        out.append(",\n".join(lines))
        out.append(");")
        out.append("")
    print(f"-- {len(tables)} tables, skipped {sorted(SKIP_TABLES)}", file=sys.stderr)
    sys.stdout.write("\n".join(out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
