-- Generated by scripts/pg_schema_gen.py — P1.1 DB convergence (DuckDB -> PG).
-- Non-destructive: creates the `stratum` schema; does NOT touch `aii`.
CREATE EXTENSION IF NOT EXISTS vector;
CREATE SCHEMA IF NOT EXISTS stratum;

CREATE TABLE IF NOT EXISTS stratum.agent_runs_sl (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "corpus_id" TEXT,
    "agent_name" TEXT NOT NULL,
    "params" JSONB,
    "status" TEXT NOT NULL,
    "started_at" TIMESTAMPTZ,
    "completed_at" TIMESTAMPTZ,
    "total_input_tokens" INTEGER,
    "total_output_tokens" INTEGER,
    "cost_usd" DOUBLE PRECISION,
    "error" TEXT,
    "trace" JSONB,
    "citations" JSONB,
    "files_generated" JSONB
);

CREATE TABLE IF NOT EXISTS stratum.aii_processed_needs (
    "id" TEXT PRIMARY KEY,
    "need_hash" TEXT NOT NULL,
    "topic" TEXT,
    "source_type" TEXT,
    "sub_id" TEXT,
    "result" TEXT,
    "miss_rounds" INTEGER,
    "notes" TEXT,
    "processed_at" TIMESTAMPTZ,
    "ingested_count" INTEGER
);

CREATE TABLE IF NOT EXISTS stratum.arxiv_processed_papers (
    "subscription_id" TEXT NOT NULL,
    "arxiv_id" TEXT NOT NULL,
    "processed_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.arxiv_subscriptions (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "name" TEXT,
    "categories_json" TEXT,
    "keywords" TEXT,
    "author" TEXT,
    "after_date" TEXT,
    "max_results" INTEGER,
    "llm_filter" TEXT,
    "status" TEXT,
    "scan_status" TEXT,
    "last_check" TIMESTAMPTZ,
    "found_count" INTEGER,
    "ingested_count" INTEGER,
    "current_paper" TEXT,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.auth_events (
    "id" TEXT PRIMARY KEY,
    "event_type" TEXT NOT NULL,
    "ip_address" TEXT NOT NULL,
    "user_id" TEXT,
    "user_agent" TEXT,
    "created_at" TIMESTAMPTZ,
    "meta_json" TEXT
);

CREATE TABLE IF NOT EXISTS stratum.blocked_ips (
    "ip_address" TEXT PRIMARY KEY,
    "reason" TEXT NOT NULL,
    "blocked_at" TIMESTAMPTZ,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "blocked_count" INTEGER
);

CREATE TABLE IF NOT EXISTS stratum.changefeed (
    "seq" BIGINT PRIMARY KEY,
    "event_id" TEXT NOT NULL,
    "user_id" TEXT NOT NULL,
    "device_id" TEXT NOT NULL,
    "timestamp" TIMESTAMPTZ NOT NULL,
    "event_type" TEXT NOT NULL,
    "payload" JSONB,
    "processed" BOOLEAN
);

CREATE TABLE IF NOT EXISTS stratum.changefeed_local (
    "seq" BIGINT PRIMARY KEY,
    "table_name" TEXT NOT NULL,
    "row_id" TEXT NOT NULL,
    "op" TEXT NOT NULL,
    "payload" JSONB,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.channel_processed_videos (
    "subscription_id" TEXT NOT NULL,
    "video_id" TEXT NOT NULL,
    "processed_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.channel_subscriptions (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "channel_url" TEXT NOT NULL,
    "channel_title" TEXT,
    "rules_json" JSONB,
    "status" TEXT,
    "last_check" TIMESTAMPTZ,
    "scan_status" TEXT,
    "found_count" INTEGER,
    "ingested_count" INTEGER,
    "current_video" TEXT,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.concepts (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "aliases" TEXT[],
    "wikilink" TEXT,
    "substrate_refs" TEXT[],
    "related_concept_ids" TEXT[],
    "created_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.derivative (
    "id" TEXT PRIMARY KEY,
    "substrate_id" TEXT NOT NULL,
    "kind" TEXT NOT NULL,
    "seq" INTEGER,
    "content" TEXT,
    "embedding_id" TEXT,
    "embedding_dim" INTEGER,
    "meta_json" JSONB,
    "created_at" TIMESTAMPTZ,
    "corpus_id" TEXT,
    "medium" TEXT,
    "file_path" TEXT
);

CREATE TABLE IF NOT EXISTS stratum.feed_subscriptions (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "feed_url" TEXT NOT NULL,
    "feed_title" TEXT,
    "feed_description" TEXT,
    "frequency_hours" INTEGER,
    "last_check_at" TIMESTAMPTZ,
    "last_etag" TEXT,
    "last_modified" TEXT,
    "last_entries_count" INTEGER,
    "status" TEXT,
    "error_message" TEXT,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);

CREATE TABLE IF NOT EXISTS stratum.feedback (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "page_url" TEXT,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.folder_watches (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "path" TEXT NOT NULL,
    "description" TEXT,
    "status" TEXT,
    "last_scan_at" TIMESTAMPTZ,
    "file_count" INTEGER,
    "created_at" TIMESTAMPTZ,
    "scanned_count" INTEGER,
    "ingested_count" INTEGER,
    "current_file" TEXT,
    "scan_status" TEXT,
    "generate_derivatives" JSONB
);

CREATE TABLE IF NOT EXISTS stratum.graph_entities (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "entity_type" TEXT,
    "description" TEXT,
    "aliases" JSONB,
    "source_substrate_ids" JSONB,
    "mention_count" INTEGER,
    "embedding_id" TEXT,
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.graph_relations (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "source_entity_id" TEXT NOT NULL,
    "target_entity_id" TEXT NOT NULL,
    "relation_type" TEXT,
    "description" TEXT,
    "weight" DOUBLE PRECISION,
    "source_substrate_ids" JSONB,
    "confidence" DOUBLE PRECISION,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.highlights (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "substrate_id" TEXT NOT NULL,
    "color" TEXT,
    "text" TEXT NOT NULL,
    "note" TEXT,
    "location_json" JSONB,
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.notes_sl (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "content_markdown" TEXT,
    "substrate_refs" TEXT[],
    "concept_refs" TEXT[],
    "content_refs" TEXT[],
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.platform_concepts (
    "id" TEXT PRIMARY KEY,
    "label" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "definition" TEXT,
    "hevi_perspective" TEXT,
    "applicability" TEXT,
    "common_mistakes" TEXT,
    "related_concept_ids" TEXT[],
    "domain" TEXT[],
    "version" INTEGER,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.platform_content (
    "id" TEXT PRIMARY KEY,
    "type" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "author" TEXT,
    "body_markdown" TEXT,
    "body_html" TEXT,
    "audio_url" TEXT,
    "duration_seconds" INTEGER,
    "published_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ,
    "version" INTEGER,
    "domain" TEXT[],
    "tags" TEXT[],
    "related_content_ids" TEXT[],
    "related_concepts" TEXT[],
    "access_tier" TEXT NOT NULL,
    "deleted_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.platform_content_chunk (
    "id" TEXT PRIMARY KEY,
    "content_id" TEXT NOT NULL,
    "chunk_idx" INTEGER NOT NULL,
    "text" TEXT NOT NULL,
    "chunk_meta" JSONB,
    "embedding" vector(1024)
);

CREATE TABLE IF NOT EXISTS stratum.recommendations (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "content_id" TEXT NOT NULL,
    "score" DOUBLE PRECISION NOT NULL,
    "reason" TEXT,
    "is_read" BOOLEAN,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.scheduled_job_runs_sl (
    "id" TEXT PRIMARY KEY,
    "job_id" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "started_at" TIMESTAMPTZ,
    "completed_at" TIMESTAMPTZ,
    "error" JSONB,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.scheduled_jobs_sl (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "agent_name" TEXT NOT NULL,
    "cron_expression" TEXT NOT NULL,
    "timezone" TEXT NOT NULL,
    "enabled" BOOLEAN NOT NULL,
    "max_items" INTEGER,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.sessions (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "refresh_token_hash" TEXT NOT NULL,
    "user_agent" TEXT,
    "ip_address" TEXT,
    "expires_at" TIMESTAMPTZ NOT NULL,
    "revoked_at" TIMESTAMPTZ,
    "created_at" TIMESTAMPTZ,
    "last_used_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.share_tokens (
    "token" TEXT PRIMARY KEY,
    "resource_type" TEXT NOT NULL,
    "resource_id" TEXT NOT NULL,
    "corpus_id" TEXT NOT NULL,
    "created_by" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ,
    "expires_at" TIMESTAMPTZ,
    "revoked_at" TIMESTAMPTZ,
    "access_count" INTEGER,
    "last_accessed_at" TIMESTAMPTZ,
    "allow_anonymous" BOOLEAN,
    "meta_json" TEXT
);

CREATE TABLE IF NOT EXISTS stratum.source_processed_items (
    "subscription_id" TEXT NOT NULL,
    "external_id" TEXT NOT NULL,
    "processed_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.source_subscriptions (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "source_type" TEXT NOT NULL,
    "name" TEXT,
    "query_json" TEXT,
    "max_results" INTEGER,
    "status" TEXT,
    "scan_status" TEXT,
    "last_check" TIMESTAMPTZ,
    "found_count" INTEGER,
    "ingested_count" INTEGER,
    "current_item" TEXT,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.subscriptions (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "tier" TEXT NOT NULL,
    "plan" TEXT NOT NULL,
    "status" TEXT NOT NULL,
    "started_at" TIMESTAMPTZ NOT NULL,
    "expires_at" TIMESTAMPTZ,
    "cancelled_at" TIMESTAMPTZ,
    "payment_provider" TEXT,
    "payment_ref" TEXT,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.substrates (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "title" TEXT,
    "mime" TEXT,
    "source_path" TEXT,
    "file_hash" TEXT,
    "byte_size" BIGINT,
    "page_count" INTEGER,
    "parser" TEXT,
    "language" TEXT,
    "has_cjk" BOOLEAN,
    "is_scanned" BOOLEAN,
    "is_pinned" BOOLEAN,
    "pinned_at" TIMESTAMPTZ,
    "pin_priority" INTEGER,
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ,
    "meta_json" JSONB,
    "source" TEXT,
    "published_at" TIMESTAMPTZ,
    "parse_quality" TEXT,
    "quality_reason" TEXT
);

CREATE TABLE IF NOT EXISTS stratum.tasks (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "text" TEXT NOT NULL,
    "completed" BOOLEAN,
    "due_date" DATE,
    "scheduled_date" DATE,
    "tags" TEXT,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.templates (
    "id" TEXT PRIMARY KEY,
    "name" TEXT NOT NULL,
    "content" TEXT NOT NULL,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.user_content_interaction (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "content_id" TEXT NOT NULL,
    "interaction_type" TEXT NOT NULL,
    "payload" JSONB,
    "created_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.user_profiles (
    "user_id" TEXT PRIMARY KEY,
    "display_name" TEXT,
    "avatar_url" TEXT,
    "bio" TEXT,
    "location" TEXT,
    "website" TEXT,
    "timezone" TEXT,
    "locale" TEXT,
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.user_saved_views (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "is_preset" BOOLEAN,
    "icon" TEXT,
    "filter_json" JSONB,
    "sort_by" TEXT,
    "sort_order" TEXT,
    "display_mode" TEXT,
    "position" INTEGER,
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.user_views (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "default_filter" JSONB,
    "default_llm" JSONB,
    "default_system_prompt" TEXT,
    "default_agents" JSONB,
    "icon" TEXT,
    "is_default" BOOLEAN,
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS stratum.users (
    "id" TEXT PRIMARY KEY,
    "email" TEXT NOT NULL,
    "username" TEXT NOT NULL,
    "password_hash" TEXT NOT NULL,
    "corpus_id" TEXT NOT NULL,
    "email_verified" BOOLEAN,
    "is_active" BOOLEAN,
    "is_suspended" BOOLEAN,
    "created_at" TIMESTAMPTZ,
    "updated_at" TIMESTAMPTZ,
    "last_login_at" TIMESTAMPTZ,
    "meta_json" TEXT
);

CREATE TABLE IF NOT EXISTS stratum.views (
    "id" TEXT PRIMARY KEY,
    "user_id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "description" TEXT,
    "default_filter" TEXT,
    "default_llm" TEXT,
    "default_system_prompt" TEXT,
    "icon" TEXT,
    "is_default" BOOLEAN,
    "is_builtin" BOOLEAN,
    "created_at" TIMESTAMPTZ NOT NULL,
    "updated_at" TIMESTAMPTZ NOT NULL
);
